base: &BASE

    dataname: 'raw'
    valname: 'raw'
    img_dim: 128
    noise_vect_len: 64
    specnorm: False
    nlayers: 4
    convkern: 5
    convstride: 2
    nconvfilters: [32, 64, 128, 256]
    ndeconvfilters: [128, 64, 32, 1]
    label_flip: 0.01
    batchsize: 64
    print_batch: 20
    checkpt_batch: 150
    cscale: 'lin'
    datascale: 'lin'
    learn_rate: [0.0002, 0.0002]
    DG_update_ratio: 2
    resume: False
    Nepochs: 1000
    loss: 'binary_crossentropy'
    weight_hists: False
    grad_hists: False
    sigma_plot: False
    doubleconv: False
    datafmt: 'channels_last'

SN: &SN
    <<: *BASE
    dataname: 'crop'
    valname: 'crop'
    cscale: 'pwr'
    specnorm: True


bigSN: &bigSN
    <<: *SN
    dataname: 'fullcrop'
    valname: 'fullcrop'
    nconvfilters: [64, 128, 256, 512]
    ndeconvfilters: [256, 128, 64, 1]
    Nepochs: 70
    specnorm: True
    datafmt: 'channels_last'

bigJC:
    <<: *bigSN

bigSN_256: &bigSN_256
    <<: *bigSN
    dataname: 'full'
    valname: 'full'
    Nepochs: 70
    img_dim: 256

bigJC_256:
    <<: *bigSN_256
    specnorm: False

bigSN_noBN:
    <<: *bigSN
    Nepochs: 100
    sigma_plot: True

bigSN_TTUR: &bigSN_TTUR
    <<: *bigSN
    learn_rate: [0.0002, 0.0004]

bigSN_TTUR_cont:
    <<: *bigSN_TTUR
    resume: {'D':'./expts/bigSN_TTUR/models/d_cosmo_best.h5', 'G':'./expts/bigSN_TTUR/models/g_cosmo_best.h5'}
    Nepochs: 70
    sigma_plot: False


bignoSN: &bignoSN
    <<: *bigSN
    specnorm: False

bignoSN_256: &bignoSN_256
    <<: *bignoSN
    Nepochs: 70
    dataname: 'full'
    valname: 'full'
    img_dim: 256
    label_flip: 0.01

bigSNhinge: &bigSNhinge
    <<: *bigSN
    loss: 'hinge'
    label_flip: 0.05

bigWGP_256: 
    <<: *bignoSN_256
    label_flip: 0.0
    DG_update_ratio: 10
    batchsize: 32



